Vagrant.configure("2") do |config|
config.vm.define :servidor1 do |servidor1|
servidor1.vm.box = "bento/centos-7.9"
servidor1.vm.network :private_network, ip: "192.168.50.2"
servidor1.vm.hostname = "servidor1"
end
config.vm.define :servidor2 do |servidor2|
servidor2.vm.box = "bento/centos-7.9"
servidor2.vm.network :private_network, ip: "192.168.50.3"
servidor2.vm.hostname = "servidor2"
end
config.vm.define :firewall do |firewall|
firewall.vm.box = "bento/centos-7.9"
firewall.vm.network :public_network, ip: "192.168.0.125"
firewall.vm.network :private_network, ip: "192.168.50.4"
firewall.vm.network "forwarded_port",guest: 80,host: 5080
firewall.vm.hostname = "firewall"
end
end
